language: cpp
compiler:
  - gcc
env:

before_install:
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -y -qq autoconf automake libtool make gcc-4.8 g++-4.8 libboost1.54-all-dev lcov
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
before_script:
  - echo "Boost $(dpkg -s libboost-dev | grep 'Version')"
script:
  ./autogen.sh && ./configure --enable-coverage && make test -j2
after_failure:
  - cat config.log
