sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
env:
before_install:
  - export LD_LIBRARY_PATH=.:`cat /etc/ld.so.conf.d/* | grep -vF "#" | tr "\\n" ":" | sed -e "s/:$//g"`
install:
  - sudo apt-get install -y -qq autoconf automake libtool make gcc g++ lcov libcurl4-openssl-dev libzmq3-dev
before_script:
script:
  ./autogen.sh && ./configure --enable-coverage && make test -j4
after_failure:
  - cat config.log
  - cat test/*.log
