language: cpp
compiler:
  - gcc
env:
  - LD_LIBRARY_PATH=.:`cat /etc/ld.so.conf.d/* | grep -v -E "#" | tr "\\n" ":" | sed -e "s/:$//g"`
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - git clone https://github.com/zeromq/libzmq.git
install:
  - sudo apt-get install -y -qq autoconf automake libtool make gcc-4.8 g++-4.8 lcov
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - cd libzmq && ./autogen.sh && ./configure --without-libsodium && make -j2 && sudo make install && cd ..
before_script:
script:
  ./autogen.sh && ./configure --enable-coverage && make test -j2
after_failure:
  - cat config.log
  - cat test/*.log
