sudo: required
language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      before_install:
        - export LD_LIBRARY_PATH=.:`cat /etc/ld.so.conf.d/* | grep -vF "#" | tr "\\n" ":" | sed -e "s/:$//g"`
        - sudo add-apt-repository -y ppa:kevinkreiser/libsodium
        - sudo add-apt-repository -y ppa:kevinkreiser/libpgm
        - sudo add-apt-repository -y ppa:kevinkreiser/zeromq3
        - sudo add-apt-repository -y ppa:kevinkreiser/czmq
        - sudo apt-get update
      install:
        - sudo apt-get install -y -qq autoconf automake libtool make gcc g++ lcov libcurl4-openssl-dev libzmq3-dev libczmq-dev
      script:
        - ./autogen.sh && ./configure --enable-coverage && make test -j$(nproc)
    - os: osx
      compiler: clang
      before_install:
        - brew update
      install:
        - brew install automake libtool zeromq czmq
      script:
        - ./autogen.sh && ./configure && make -j test
after_failure:
  - cat config.log
  - cat test/*.log
